<?php

namespace Statistics\OperationsManagement\Operations\RelationshipEasyLoaders\OperationGroupRelationshipLoaders;


use Statistics\OperationsManagement\Operations\RelationshipEasyLoaders\OperationGroupRelationshipLoaders\Traits\RelationshipFilteredColumnMethods;

class RelationshipFilteredColumnLoader extends RelationshipColumnsLoader
{
    use RelationshipFilteredColumnMethods;
}
