<?php

namespace Statistics\QueryCustomizationStrategies\DateGroupedChartQueryCustomizers\DateGroupedChartAvgQueryCustomizers;

use DataResourceInstructors\OperationComponents\Columns\Column;
use DataResourceInstructors\OperationContainers\OperationGroups\OperationGroup;
use DataResourceInstructors\OperationTypes\AggregationOperation;
use Illuminate\Database\Query\Builder;
use Statistics\DateProcessors\DateProcessor;
use Statistics\QueryCustomizationStrategies\DateGroupedChartQueryCustomizers\DateGroupedChartQueryCustomizer;
use Statistics\QueryCustomizationStrategies\QueryCustomizationStrategy;

abstract class DateGroupedChartAvgQueryCustomizer extends DateGroupedChartQueryCustomizer
{
 

}
