<?php

namespace Statistics\QueryCustomizationStrategies\DateGroupedChartQueryCustomizers\DateGroupedChartAvgQueryCustomizers;

use Statistics\QueryCustomizationStrategies\DateGroupedChartQueryCustomizers\DateGroupedChartQueryCustomizer;

abstract class DateGroupedChartAvgQueryCustomizer extends DateGroupedChartQueryCustomizer
{
 

}
