<?php

namespace Statistics\QueryCustomizationStrategies\DateGroupedChartQueryCustomizers\DateGroupedChartSumQueryCustomizers;

use Statistics\QueryCustomizationStrategies\DateGroupedChartQueryCustomizers\DateGroupedChartQueryCustomizer;


abstract class DateGroupedChartSumQueryCustomizer extends DateGroupedChartQueryCustomizer
{
 

}
