<?php

namespace Statistics\QueryCustomizationStrategies\DateGroupedChartQueryCustomizers\DateGroupedChartCountQueryCustomizers;

use Statistics\QueryCustomizationStrategies\DateGroupedChartQueryCustomizers\DateGroupedChartQueryCustomizer;


abstract class DateGroupedChartCountQueryCustomizer extends DateGroupedChartQueryCustomizer
{


}
